### PR TITLE
P4 2081 bulk load moves

### PR DESCRIPTION
**Pull request by martyn-w**
### Jira link

P4-2081

### What?

I have added/removed/altered:

- [x] Added a rake task to bulk load N identical moves, for load testing

### Why?

I am doing this because:

- so we can load test

### Deployment risks (optional)

- none

### CODE REVIEW

**Review by smoothcontract — COMMENTED** [review]
This seems like a strange approach to adopt just for some test data - creating these via the API is going to be a bit slow, and seems to be replicating logic that we already have in the `fake_data` rake tasks.. rather than adding this new code would you consider adapting the existing fake data tasks, or building something along similar lines that leverages FactoryBot fixtures and Faker, creating records directly rather than via the API?

**Comment by martyn-w** [comment]
@smoothcontract thanks for the review. The point here was to load directly via the API (rather than at a lower level) in order to load-test the system, and also to load-test the resulting webhooks sent to suppliers.

**Comment by smoothcontract** [comment]
> @smoothcontract thanks for the review. The point here was to load directly via the API (rather than at a lower level) in order to load-test the system, and also to load-test the resulting webhooks sent to suppliers.

Fair enough, I misunderstood the intent of this PR then. I thought this was simply setting up a large volume of data to then perform load testing against, but this is actually performing the load testing too? If that's the case then that's also a slightly odd approach as there are plenty of great tools to do this rather than hand cranking stuff in Ruby.

**Comment by martyn-w** [comment]
Closing for now, will revisit later.

**Pull request closed without merging**
