### PR TITLE
Adds supplier relationship to generic_event

### PR DESCRIPTION
**Pull request by willfish**
### Jira link

P4-<TODO>

### What?

I have added/removed/altered:

- [x] Adds supplier relationship to generic event

### Why?

I am doing this because:

- We want to make sure we're including the supplier that is currently present in the v1 apis on every generic event.

### CODE REVIEW

**Comment by martyn-w** [comment]
will you need a task to update existing generic events copied over from v1 to import the supplier?

**Comment by willfish** [comment]
I'll be doing that separately/rolling back/updating the copier/updating newly dual-written generic events to include this

**Review by alexdesi — APPROVED** [review]
💯

**Review by martyn-w — APPROVED** [review]
👍

**Pull request merged**
